[package]
name = "Traversy_Tut"
version = "0.1.0"
authors = ["Sachin Umrao <sachin.umrao.1512@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
